### ISSUE TITLE
dev branch pytest wont run

### ISSUE THREAD

**Issue by dhavala** [mlsquare/mlsquare#13]
and circle CI build is failing
pytest
1) clone dev branch
2) run python setup.py develop
3) run pytest
produces following error

ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov --cov-report term-missing mlsquare
  inifile: /path/mlsquare/setup.cfg
  rootdir: /path/mlsq/mlsquare

**Comment by shakkeel1330** [comment]
Can you share the `pytest` and `pyscaffold` versions?

**Comment by shakkeel1330** [comment]
This works fine when I tested locally.

![Screenshot from 2019-09-25 16-17-27](https://user-images.githubusercontent.com/20453165/65594603-c8589f00-dfb0-11e9-8bb2-e0f995a311ed.png)
![Screenshot from 2019-09-25 16-17-34](https://user-images.githubusercontent.com/20453165/65594614-cdb5e980-dfb0-11e9-814a-114e04442489.png)

**Comment by dhavala** [comment]
pytest==4.4.0
pytest-runner==5.1
pyscaffold-3.2.2

btw, builder badge is failing on /dev branch

**Comment by shakkeel1330** [comment]
Can you try `python setup.py test`?
The build is failing due to a tune-redis config param. Working on it.
